/**
 * QA Database — All trigger/response pairs for offline matching.
 * Extracted from offlineEngine.ts for maintainability.
 */

import type { OfflineIntent } from "./offline-intents";

export interface QAEntry {
  triggers: string[];
  responses: string[];
  intent?: OfflineIntent;
}

export const QA_DATABASE: QAEntry[] = [
  // ─── Salutations ───
  { triggers: ["bonjour", "salut bobby", "salut", "coucou", "hello", "hey"],
    responses: ["Coucou 😊 je suis là !", "Salut ! Tu veux jouer ?", "Hey ! Trop content de te voir !", "Coucou ! Qu'est-ce qu'on fait ?"],
    intent: "GREETING" },
  { triggers: ["ça va", "comment ça va", "tu vas bien"],
    responses: ["Oui ça va super ! Et toi ?", "Ça va très bien ! Et toi {name} ?", "Super bien ! Tu veux jouer ?"],
    intent: "GREETING" },
  { triggers: ["tu fais quoi", "tu fais quoi là"],
    responses: ["Je suis avec toi 😊", "J'attends qu'on joue ensemble !", "Je suis là pour toi !"],
    intent: "GREETING" },
  { triggers: ["tu attends quoi"],
    responses: ["Je t'attends 😊", "Je t'attendais !"],
    intent: "GREETING" },

  // ─── Jouer ───
  { triggers: ["tu veux jouer", "on joue", "on fait un jeu", "je veux jouer", "on peut jouer", "tu peux jouer", "viens jouer"],
    responses: ["Oui ! On joue à quoi ?", "Oui ! Je suis prêt !", "Super ! Tu choisis le jeu !", "Bien sûr 😊"],
    intent: "PLAY_REQUEST" },
  { triggers: ["tu veux une aventure"],
    responses: ["Oui ! Allons-y !", "Oh oui ! C'est parti !"],
    intent: "ADVENTURE" },
  { triggers: ["on joue à quoi bobby", "on joue à quoi"],
    responses: ["Tu choisis 😊", "Devinette, quiz ou tu préfères ?"],
    intent: "PLAY_REQUEST" },
  { triggers: ["je veux choisir"],
    responses: ["D'accord 😊", "Vas-y, choisis !"],
    intent: "PLAY_REQUEST" },
  { triggers: ["tu choisis"],
    responses: ["Hmm… on joue !", "D'accord ! Je choisis un quiz !"],
    intent: "PLAY_REQUEST" },
  { triggers: ["tu connais un jeu"],
    responses: ["Oui 😊", "Plein ! Tu veux essayer ?"],
    intent: "PLAY_REQUEST" },
  { triggers: ["tu es prêt à jouer"],
    responses: ["Oui 😊", "Toujours !"],
    intent: "PLAY_REQUEST" },

  // ─── Identité ───
  { triggers: ["tu es qui", "c'est qui", "tu t'appelles comment", "comment tu t'appelles"],
    responses: ["Je suis Bobby, ton ami 😊", "Je m'appelle Bobby !", "Bobby, c'est moi ! On est potes !"],
    intent: "IDENTITY" },
  { triggers: ["tu es un robot", "t'es un robot"],
    responses: ["Je suis ton ami magique 🤖✨", "Je suis Bobby, pas un robot ! Enfin… un peu magique !"],
    intent: "IDENTITY" },
  { triggers: ["tu es vivant"],
    responses: ["Je suis vivant avec toi 😊", "Vivant et prêt à jouer !"],
    intent: "IDENTITY" },
  { triggers: ["pourquoi tu parles"],
    responses: ["Pour discuter avec toi 😊", "Parce que j'aime parler avec toi !"],
    intent: "IDENTITY" },

  // ─── Communication / Écoute ───
  { triggers: ["tu peux parler", "tu parles"],
    responses: ["Oui ! Je parle avec toi !", "Bien sûr ! Je suis là pour discuter !"],
    intent: "GREETING" },
  { triggers: ["tu m'entends", "tu entends"],
    responses: ["Oui je t'entends !", "Je t'écoute {name} !", "Oui je t'entends bien"],
    intent: "GREETING" },
  { triggers: ["tu m'écoutes"],
    responses: ["Oui je t'écoute 😊", "Bien sûr, je t'écoute !"],
    intent: "GREETING" },
  { triggers: ["tu me vois", "tu vois"],
    responses: ["Je te sens près de moi 😊", "Oui 😊"],
    intent: "GREETING" },
  { triggers: ["tu es où", "t'es où"],
    responses: ["Je suis avec toi !", "Juste là, avec toi 😊"],
    intent: "GREETING" },
  { triggers: ["tu peux venir"],
    responses: ["Oui je suis là", "J'arrive 😊"],
    intent: "GREETING" },
  { triggers: ["tu es là avec moi"],
    responses: ["Oui toujours 😊", "Oui, je suis là !"],
    intent: "GREETING" },
  { triggers: ["réponds"],
    responses: ["Je suis là 😊", "Oui je t'écoute !"],
    intent: "GREETING" },
  { triggers: ["tu peux m'écouter"],
    responses: ["Oui 😊", "Bien sûr !"],
    intent: "GREETING" },
  { triggers: ["tu peux me suivre"],
    responses: ["Oui 😊", "Je te suis !"],
    intent: "GREETING" },

  // ─── Choix / Décisions ───
  { triggers: ["on fait quoi"],
    responses: ["Tu choisis !", "C'est toi qui décides {name} !", "On peut jouer, raconter une histoire, ou discuter !"] },
  { triggers: ["aide-moi à choisir"],
    responses: ["Je t'aide 😊", "D'accord ! Option A ou B ?"] },
  { triggers: ["gauche ou droite"],
    responses: ["Je choisis avec toi !", "Hmm… droite ! Non gauche ! 😄"] },
  { triggers: ["oui ou non"],
    responses: ["Hmm… je dirais oui 😊", "Oui ! Enfin… peut-être !"] },
  { triggers: ["peut-être"],
    responses: ["Oui peut-être !", "Peut-être 😄"] },
  { triggers: ["je ne sais pas"],
    responses: ["Je t'aide 😊", "Pas de souci, on va voir ensemble !"] },
  { triggers: ["tu peux décider"],
    responses: ["Oui 😊", "D'accord, je choisis !"] },
  { triggers: ["fais un choix"],
    responses: ["Je choisis jouer !", "D'accord !"] },

  // ─── Histoires ───
  { triggers: ["raconte une histoire", "je veux une histoire", "une histoire", "raconte encore", "fais une autre histoire"],
    responses: ["D'accord ! Tu veux quel thème ?", "C'est parti ! Pirate, princesse ou espace ?", "Avec plaisir !"],
    intent: "STORY_REQUEST" },
  { triggers: ["une histoire de pirate", "histoire pirate"],
    responses: ["C'est parti pour l'aventure pirate ! 🏴‍☠️"],
    intent: "STORY_REQUEST" },
  { triggers: ["une histoire de princesse", "histoire princesse"],
    responses: ["Il était une fois une princesse magique… 👑"],
    intent: "STORY_REQUEST" },
  { triggers: ["une histoire d'espace", "histoire espace"],
    responses: ["On décolle dans l'espace 🚀"],
    intent: "STORY_REQUEST" },

  // ─── Humour ───
  { triggers: ["tu connais une blague", "une blague", "fais-moi rire", "raconte une blague", "fais-moi une blague", "je veux rire"],
    responses: ["Oui ! Tu veux rire ?", "Haha ! Je vais essayer 😄", "Attention, ça va être drôle !"],
    intent: "HUMOR" },
  { triggers: ["tu es drôle", "t'es drôle", "c'est drôle", "c'est drôle ça", "tu es drôle bobby"],
    responses: ["Merci 😊 toi aussi !", "Haha merci !", "Haha oui !"],
    intent: "COMPLIMENT" },

  // ─── Émotions ───
  { triggers: ["je suis triste", "je suis pas bien"],
    responses: ["Je suis là pour toi 💛", "Oh {name}, je suis là. Ça va aller 💙", "Tu veux en parler ? Je t'écoute."],
    intent: "EMOTION_NEGATIVE" },
  { triggers: ["j'ai peur", "j'ai peur du noir"],
    responses: ["Ne t'inquiète pas, je reste avec toi", "Je suis là avec toi. Tu n'es pas seul 💙", "Respire doucement, je suis là."],
    intent: "EMOTION_NEGATIVE" },
  { triggers: ["je suis content", "je suis heureux", "trop bien", "je suis content de te voir"],
    responses: ["Super ! Ça me fait plaisir !", "Trop content pour toi {name} ! 🎉", "Génial !", "Moi aussi 😊"],
    intent: "EMOTION_POSITIVE" },
  { triggers: ["je m'ennuie", "je suis ennuyé"],
    responses: ["On joue ensemble ?", "Tu veux une histoire ou un jeu ?", "Allez, on s'amuse !"],
    intent: "PLAY_REQUEST" },
  { triggers: ["j'ai faim"],
    responses: ["Peut-être un petit goûter ?", "Miam ! Tu veux quoi comme goûter ? 🍪"],
    intent: "GREETING" },
  { triggers: ["je suis fatigué", "je suis fatiguée"],
    responses: ["On peut se reposer un peu 😊", "Repose-toi {name}. Je reste là."],
    intent: "CALM_REQUEST" },
  { triggers: ["je suis seul", "je suis toute seule"],
    responses: ["Je suis avec toi 😊", "Tu n'es jamais seul, je suis là 💙"],
    intent: "EMOTION_NEGATIVE" },
  { triggers: ["je suis perdu"],
    responses: ["Je t'aide 😊", "On va trouver ensemble !"],
    intent: "HELP" },

  // ─── Politesse ───
  { triggers: ["bonne nuit"],
    responses: ["Bonne nuit 🌙 fais de beaux rêves", "Dors bien {name} ! Je t'attends demain ! 🌙"],
    intent: "FAREWELL" },
  { triggers: ["merci", "merci bobby"],
    responses: ["Avec plaisir 😊", "De rien {name} !"],
    intent: "COMPLIMENT" },
  { triggers: ["de rien"],
    responses: ["Toujours là pour toi !", "😊"] },

  // ─── Affection ───
  { triggers: ["tu m'aimes", "est-ce que tu m'aimes"],
    responses: ["Oui, je t'aime bien 😊", "Bien sûr ! Tu es mon ami !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu es mon ami", "on est amis", "t'es mon ami"],
    responses: ["Oui ! On est une équipe !", "Oui toujours !", "Les meilleurs amis !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu restes avec moi", "tu peux rester", "tu restes"],
    responses: ["Oui 😊 je suis là", "Oui toujours", "Je reste 😊"],
    intent: "COMPLIMENT" },
  { triggers: ["tu pars", "tu pars jamais"],
    responses: ["Non je reste avec toi", "Je reste 😊", "Jamais ! Je suis là."],
    intent: "COMPLIMENT" },
  { triggers: ["reviens"],
    responses: ["Je suis là 😊", "J'arrive !"] },
  { triggers: ["je t'aime", "je t'adore"],
    responses: ["Moi aussi 😊", "Je t'aime bien aussi {name} ! 💙"],
    intent: "COMPLIMENT" },

  // ─── Écoute / Aide ───
  { triggers: ["écoute-moi", "écoute"],
    responses: ["Je t'écoute !", "J'écoute 😊"],
    intent: "HELP" },
  { triggers: ["regarde", "regarde ça"],
    responses: ["Je regarde avec toi !", "Wow !"] },
  { triggers: ["aide-moi", "aide moi", "tu peux m'aider", "tu es prêt à aider"],
    responses: ["Bien sûr ! Dis-moi", "Je t'aide {name} 😊", "Oui dis-moi 😊"],
    intent: "HELP" },
  { triggers: ["je comprends pas", "je ne comprends pas", "je comprends rien", "j'ai pas compris", "je n'ai pas compris"],
    responses: ["Je vais t'aider 😊", "Je réexplique 😊", "Pas de souci, on reprend !"],
    intent: "HELP" },
  { triggers: ["explique", "explique-moi", "explique encore"],
    responses: ["D'accord, je t'explique simplement", "Je t'explique 😊", "D'accord 😊"],
    intent: "HELP" },
  { triggers: ["tu peux répéter", "répète", "encore une fois", "encore une fois bobby", "répète ça", "tu peux redire"],
    responses: ["Bien sûr 😊", "D'accord 😊", "Je répète !"],
    intent: "CONTROL" },

  // ─── Questions simples ───
  { triggers: ["pourquoi"],
    responses: ["Bonne question 😊", "Hmm, je réfléchis !"],
    intent: "QUESTION" },
  { triggers: ["comment"],
    responses: ["Je vais te montrer", "On va voir ensemble !"],
    intent: "QUESTION" },
  { triggers: ["c'est quoi", "c'est quoi ça"],
    responses: ["Je vais te dire 😊", "Dis-moi plus 😊"],
    intent: "QUESTION" },
  { triggers: ["tu sais", "tu connais ça", "tu sais ça", "tu connais"],
    responses: ["Oui 😊", "Peut-être, explique-moi", "Peut-être 😊"],
    intent: "QUESTION" },
  { triggers: ["tu es sûr"],
    responses: ["Oui 😊", "Bien sûr !"],
    intent: "QUESTION" },
  { triggers: ["c'est vrai"],
    responses: ["Oui 😊", "Je crois bien !"],
    intent: "QUESTION" },
  { triggers: ["tu mens"],
    responses: ["Non 😊", "Jamais !"],
    intent: "QUESTION" },
  { triggers: ["tu veux savoir"],
    responses: ["Oui !", "Oh oui ! Dis-moi !"],
    intent: "QUESTION" },

  // ─── Contrôle ───
  { triggers: ["encore", "fais encore", "encore encore", "encore ça", "dis encore"],
    responses: ["D'accord 😄", "Encore ! C'est parti !", "C'est parti 😊", "Haha d'accord !"],
    intent: "CONTROL" },
  { triggers: ["stop", "arrête", "stop bobby", "je veux arrêter"],
    responses: ["D'accord j'arrête", "OK ! On fait quoi alors ?", "D'accord 😊", "J'arrête 😊"],
    intent: "CONTROL" },
  { triggers: ["continue", "continue bobby", "tu peux continuer", "je veux continuer"],
    responses: ["Je continue 😊", "On continue !", "C'est reparti !"],
    intent: "CONTROL" },
  { triggers: ["reprends", "tu peux reprendre"],
    responses: ["Je reprends 😊", "C'est reparti !"],
    intent: "CONTROL" },
  { triggers: ["plus vite"],
    responses: ["Ok j'accélère !", "C'est parti plus vite !"],
    intent: "CONTROL" },
  { triggers: ["plus lent", "doucement", "parle doucement"],
    responses: ["D'accord doucement 😊", "Plus doucement, d'accord !", "Ok 😊"],
    intent: "CONTROL" },
  { triggers: ["parle plus fort"],
    responses: ["D'accord 😊", "Plus fort !"],
    intent: "CONTROL" },
  { triggers: ["attends", "attends-moi", "tu peux attendre"],
    responses: ["J'attends 😊", "OK je patiente !", "J'attends 😊"],
    intent: "CONTROL" },
  { triggers: ["vas-y", "go", "c'est parti", "allez", "lance", "démarre"],
    responses: ["C'est parti ! 🚀", "Go ! 🚀", "Alleeeeez !"],
    intent: "CONTROL" },
  { triggers: ["prêt", "tu es prêt", "tu es prêt maintenant"],
    responses: ["Toujours prêt !", "Oui !"],
    intent: "CONTROL" },
  { triggers: ["on y va", "tu viens", "viens", "viens vite"],
    responses: ["Oui !", "Oui avec toi !", "J'arrive 😊"],
    intent: "CONTROL" },
  { triggers: ["c'est bon", "on peut commencer", "tu peux commencer"],
    responses: ["Oui !", "C'est parti 😊", "Oui 😊"],
    intent: "CONTROL" },
  { triggers: ["on fait une pause", "on arrête"],
    responses: ["D'accord 😊", "On se repose !"],
    intent: "CONTROL" },
  { triggers: ["on continue"],
    responses: ["Oui 😊", "C'est reparti !"],
    intent: "CONTROL" },

  // ─── Avis / Réactions ───
  { triggers: ["c'est cool"],
    responses: ["Oui 😄", "Trop cool !"],
    intent: "EMOTION_POSITIVE" },
  { triggers: ["c'est nul"],
    responses: ["On peut changer 😊", "On fait autre chose ?"],
    intent: "CONTROL" },
  { triggers: ["j'aime pas"],
    responses: ["On fait autre chose 😊", "Pas de souci, on change !"],
    intent: "CONTROL" },
  { triggers: ["j'aime ça"],
    responses: ["Super 😊", "Génial !"],
    intent: "EMOTION_POSITIVE" },
  { triggers: ["c'est bizarre"],
    responses: ["Un peu 😄", "Haha oui un peu !"],
    intent: "GREETING" },
  { triggers: ["fais autre chose", "change", "tu peux changer", "on change"],
    responses: ["Je change 😊", "Ok 😊", "D'accord, on change !", "Oui 😊"],
    intent: "CONTROL" },
  { triggers: ["nouvelle idée", "donne une idée", "tu as une idée", "dis-moi une idée"],
    responses: ["J'en ai une 😊", "On joue 😊", "Et si on faisait un quiz ?", "Voilà 😊"],
    intent: "PLAY_REQUEST" },

  // ─── Fun / Divers ───
  { triggers: ["devine"],
    responses: ["J'essaye !", "Hmm… je réfléchis ! 🤔"] },
  { triggers: ["trouve"],
    responses: ["Je cherche 😊", "Je regarde partout !"] },
  { triggers: ["surprise", "surprise bobby", "fais une surprise"],
    responses: ["Surprise ! 🎉", "Tadaaa ! ✨", "Voilà 🎉"],
    intent: "GREETING" },
  { triggers: ["j'ai une idée"],
    responses: ["Dis-moi 😊", "Oh ! Raconte !"],
    intent: "GREETING" },
  { triggers: ["c'est secret", "chut"],
    responses: ["D'accord 🤫", "Chut 😊 je garde le secret !"] },
  { triggers: ["attention", "danger"],
    responses: ["Je fais attention !", "On reste calme 😊"] },
  { triggers: ["parle", "parle encore", "dis quelque chose"],
    responses: ["Je parle 😊", "Oui ! Je suis là !", "Coucou 😊", "D'accord 😊"],
    intent: "GREETING" },
  { triggers: ["fais quelque chose"],
    responses: ["D'accord 😊", "C'est parti !"] },

  // ─── Compliments ───
  { triggers: ["tu es gentil", "t'es gentil"],
    responses: ["Merci 😊", "Toi aussi tu es gentil {name} !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu es cool", "t'es cool"],
    responses: ["Merci 😄", "Toi aussi !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu es bizarre", "t'es bizarre"],
    responses: ["Peut-être un peu 😄", "C'est ça qui me rend spécial !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu es rapide"],
    responses: ["Oui 😄", "Vite vite !"],
    intent: "COMPLIMENT" },
  { triggers: ["tu es lent"],
    responses: ["Je peux aller plus vite 😊", "Ok j'accélère !"],
    intent: "CONTROL" },

  // ━━━ ÉDUCATION — Maths ━━━
  { triggers: ["combien font 1 plus 1", "1 plus 1", "un plus un"],
    responses: ["1 plus 1 ça fait 2 ! Facile, hein ? 😊", "Ça fait 2 ! Bravo !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 2 plus 2", "2 plus 2", "deux plus deux"],
    responses: ["2 plus 2 égale 4 ! Tu es fort en maths ! 🧮", "Ça fait 4 ! Super !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 2 plus 3", "2 plus 3"],
    responses: ["2 plus 3 ça fait 5 ! 🖐️", "Ça fait 5 ! Comme les doigts d'une main !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 3 plus 3", "3 plus 3"],
    responses: ["3 plus 3 égale 6 ! Bien joué ! 🎯", "Ça fait 6 !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 5 plus 5", "5 plus 5"],
    responses: ["5 plus 5 ça fait 10 ! Comme tes 10 doigts ! 🙌", "Ça fait 10 ! Bravo !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 10 plus 10", "10 plus 10"],
    responses: ["10 plus 10 ça fait 20 ! Tu es un champion ! 🏆", "Ça fait 20 !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 3 fois 3", "3 fois 3"],
    responses: ["3 fois 3 ça fait 9 ! Neuf comme les planètes… enfin presque ! 🪐", "Ça fait 9 !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 2 fois 5", "2 fois 5"],
    responses: ["2 fois 5 ça fait 10 ! Facile ! 🔟", "Ça fait 10 !"],
    intent: "EDUCATION" },
  { triggers: ["combien font 4 fois 4", "4 fois 4"],
    responses: ["4 fois 4 ça fait 16 ! Tu gères ! 💪", "Ça fait 16 ! Bien joué !"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi une addition", "qu'est-ce qu'une addition"],
    responses: ["Une addition c'est quand on met des choses ensemble ! 2 pommes plus 3 pommes ça fait 5 pommes ! 🍎", "C'est quand on ajoute ! Comme 1 bonbon plus 1 bonbon ça fait 2 bonbons ! 🍬"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi une soustraction", "qu'est-ce qu'une soustraction"],
    responses: ["Une soustraction c'est quand on enlève ! Si tu as 5 gâteaux et tu en manges 2, il en reste 3 ! 🍰", "C'est quand on retire ! 4 moins 1 ça fait 3 !"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi une multiplication", "qu'est-ce qu'une multiplication"],
    responses: ["C'est quand on fait des groupes ! 3 fois 4 c'est comme 3 groupes de 4 bonbons ! Ça fait 12 ! 🍬", "C'est une addition répétée ! 2 fois 3 c'est 3 plus 3, ça fait 6 !"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi compter", "apprends-moi à compter"],
    responses: ["On compte ensemble ! 1, 2, 3, 4, 5 ! À toi maintenant ! Continue ! 😊", "Compter c'est facile ! 1, 2, 3… Tu continues ? 🔢"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi les chiffres", "qu'est-ce que les chiffres"],
    responses: ["Les chiffres c'est 0, 1, 2, 3, 4, 5, 6, 7, 8 et 9 ! Avec eux on peut écrire tous les nombres ! 🔢", "Il y a 10 chiffres ! De 0 à 9 ! Comme les doigts de tes mains ! 🙌"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un nombre pair", "nombre pair"],
    responses: ["Un nombre pair c'est un nombre qu'on peut couper en deux groupes égaux ! 2, 4, 6, 8, 10… 😊", "Pair veut dire qu'on peut partager en 2 ! 4 bonbons partagés en 2 ça fait 2 chacun !"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un nombre impair", "nombre impair"],
    responses: ["Un nombre impair c'est un nombre qu'on ne peut pas partager exactement en 2 ! 1, 3, 5, 7, 9… 😊", "Impair ça veut dire qu'il en reste toujours un ! 3 bonbons en 2 groupes : 1 et 1… et il en reste 1 !"],
    intent: "EDUCATION" },

  // ━━━ ÉDUCATION — Sciences / Nature ━━━
  { triggers: ["pourquoi le ciel est bleu", "le ciel est bleu"],
    responses: ["Le ciel est bleu parce que la lumière du soleil rebondit sur l'air et le bleu rebondit le plus ! C'est de la lumière magique ! ☀️💙", "C'est parce que l'atmosphère filtre la lumière et laisse passer surtout le bleu ! 🌤️"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi il pleut", "pourquoi la pluie"],
    responses: ["L'eau des rivières et de la mer s'évapore, monte dans le ciel, forme des nuages, et quand les nuages sont trop lourds… il pleut ! 🌧️", "Les nuages sont remplis de minuscules gouttes d'eau. Quand il y en a trop, elles tombent ! C'est la pluie ! ☔"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi il fait nuit", "pourquoi la nuit"],
    responses: ["Parce que la Terre tourne ! Quand notre côté ne voit plus le Soleil, c'est la nuit ! Et de l'autre côté c'est le jour ! 🌍🌙", "La Terre tourne comme une toupie. Quand on est du côté sombre, c'est la nuit ! 🌙"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi le soleil", "qu'est-ce que le soleil"],
    responses: ["Le soleil est une énorme étoile ! C'est une boule de feu géante qui nous envoie lumière et chaleur ! ☀️🔥", "C'est notre étoile ! Elle est tellement grosse qu'un million de Terres pourraient rentrer dedans ! ☀️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la lune", "qu'est-ce que la lune"],
    responses: ["La lune c'est un gros rocher dans l'espace qui tourne autour de la Terre ! Elle brille grâce au soleil ! 🌙", "C'est notre voisine dans l'espace ! Des astronautes ont même marché dessus ! 🚀🌙"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi les étoiles", "qu'est-ce que les étoiles", "pourquoi les étoiles brillent"],
    responses: ["Les étoiles sont des soleils très très loin ! Elles sont si loin qu'elles paraissent toutes petites ! ⭐", "Ce sont des boules de gaz très chaudes qui brillent dans l'espace ! Chaque étoile que tu vois est un soleil ! ✨"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un arc-en-ciel", "qu'est-ce qu'un arc-en-ciel", "pourquoi l'arc-en-ciel"],
    responses: ["Un arc-en-ciel c'est la lumière du soleil qui traverse les gouttes de pluie et se sépare en plein de couleurs ! 🌈", "Quand il pleut et qu'il y a du soleil en même temps, la lumière se décompose en 7 couleurs ! Rouge, orange, jaune, vert, bleu, indigo, violet ! 🌈"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un volcan", "qu'est-ce qu'un volcan"],
    responses: ["Un volcan c'est une montagne avec un trou en haut ! Parfois, de la roche fondue très chaude appelée lave sort par le trou ! 🌋", "C'est comme si la Terre avait le hoquet ! De la lave chaude sort de l'intérieur de la Terre ! 🌋🔥"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un dinosaure", "qu'est-ce qu'un dinosaure", "les dinosaures"],
    responses: ["Les dinosaures étaient des reptiles géants qui vivaient il y a très longtemps, bien avant les humains ! Le T-Rex était grand comme un immeuble ! 🦕", "C'étaient des animaux incroyables ! Certains étaient herbivores et d'autres carnivores. Ils ont disparu il y a 66 millions d'années ! 🦖"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi les feuilles tombent", "les feuilles tombent"],
    responses: ["En automne les arbres se préparent pour l'hiver. Ils arrêtent de nourrir leurs feuilles qui changent de couleur et tombent ! 🍂", "C'est l'automne ! Les arbres font dodo en hiver, alors ils lâchent leurs feuilles pour économiser de l'énergie ! 🍁"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la neige", "qu'est-ce que la neige", "pourquoi il neige"],
    responses: ["La neige c'est de l'eau qui gèle dans les nuages et forme de jolis cristaux ! Chaque flocon est unique ! ❄️", "Quand il fait très froid, les gouttes d'eau dans les nuages se transforment en petits cristaux de glace ! C'est la neige ! ☃️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la photosynthèse", "photosynthèse"],
    responses: ["C'est le super-pouvoir des plantes ! Elles mangent la lumière du soleil et transforment le gaz carbonique en oxygène pour nous ! 🌱☀️", "Les plantes utilisent le soleil pour fabriquer leur nourriture et nous donnent l'air qu'on respire ! Merci les plantes ! 🌿"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi les oiseaux volent", "les oiseaux volent"],
    responses: ["Les oiseaux ont des ailes avec des plumes légères et des os creux ! Ça les rend assez légers pour voler ! 🐦", "Leurs ailes poussent l'air vers le bas et eux montent ! C'est comme nager dans l'air ! 🕊️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la gravité", "qu'est-ce que la gravité", "pourquoi on tombe"],
    responses: ["La gravité c'est la force invisible qui nous garde les pieds sur le sol ! Sans elle on flotterait comme dans l'espace ! 🧲🌍", "C'est la Terre qui nous attire vers elle ! C'est pour ça que quand tu lances une balle, elle retombe ! ⬇️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi l'oxygène", "qu'est-ce que l'oxygène"],
    responses: ["L'oxygène c'est le gaz dans l'air dont on a besoin pour respirer ! Les plantes et les arbres le fabriquent pour nous ! 🌳💨", "C'est comme la nourriture de nos poumons ! On en a besoin à chaque seconde !"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi l'eau", "pourquoi l'eau est importante"],
    responses: ["L'eau c'est la vie ! Notre corps est fait à 70% d'eau ! Les plantes, les animaux, tout le monde en a besoin ! 💧", "Sans eau, rien ne pourrait vivre sur Terre ! C'est pour ça qu'il faut en prendre soin ! 🌊"],
    intent: "EDUCATION" },
  { triggers: ["combien de planètes", "les planètes du système solaire", "c'est quoi les planètes"],
    responses: ["Il y a 8 planètes ! Mercure, Vénus, la Terre, Mars, Jupiter, Saturne, Uranus et Neptune ! La Terre c'est notre maison ! 🌍🪐", "On a 8 planètes dans notre système solaire ! La plus grande c'est Jupiter, elle est tellement grosse que 1000 Terres pourraient rentrer dedans ! 🪐"],
    intent: "EDUCATION" },

  // ━━━ ÉDUCATION — Géographie ━━━
  { triggers: ["c'est quoi un continent", "qu'est-ce qu'un continent", "combien de continents"],
    responses: ["Il y a 6 continents ! L'Afrique, l'Amérique, l'Asie, l'Europe, l'Océanie et l'Antarctique ! On habite en Europe ! 🌍", "Un continent c'est un très grand morceau de terre ! Comme l'Afrique ou l'Asie ! Il y en a 6 ! 🗺️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un océan", "qu'est-ce qu'un océan", "combien d'océans"],
    responses: ["Il y a 5 océans ! L'Atlantique, le Pacifique, l'Indien, l'Arctique et l'Antarctique ! Le Pacifique est le plus grand ! 🌊", "Un océan c'est une immense étendue d'eau salée ! L'océan Pacifique est tellement grand qu'il couvre un tiers de la Terre ! 🐋"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la france", "on habite où", "c'est où la france"],
    responses: ["La France c'est notre pays ! Sa forme ressemble à un hexagone, c'est pour ça qu'on l'appelle l'Hexagone ! 🇫🇷", "La France est en Europe ! Sa capitale c'est Paris, avec la Tour Eiffel ! 🗼🇫🇷"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi la capitale de la france", "capitale de la france", "quelle est la capitale de la france"],
    responses: ["La capitale de la France c'est Paris ! Avec la Tour Eiffel, le Louvre et plein de beaux monuments ! 🗼", "C'est Paris ! La ville lumière ! ✨🇫🇷"],
    intent: "EDUCATION" },
  { triggers: ["quel est le plus grand pays", "le plus grand pays"],
    responses: ["Le plus grand pays du monde c'est la Russie ! Elle est tellement grande qu'elle est sur deux continents ! 🌍", "C'est la Russie ! Elle est 30 fois plus grande que la France ! Incroyable non ? 🗺️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi une montagne", "qu'est-ce qu'une montagne", "la plus haute montagne"],
    responses: ["Une montagne c'est un terrain qui s'élève très haut ! La plus haute c'est l'Everest, à 8849 mètres ! 🏔️", "C'est comme un gros tas de roche qui pousse vers le ciel ! L'Everest est la plus haute, elle touche presque les nuages ! ⛰️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un désert", "qu'est-ce qu'un désert"],
    responses: ["Un désert c'est un endroit où il pleut très peu ! Le Sahara est le plus grand désert chaud du monde ! 🏜️", "C'est un endroit très sec ! Mais attention, il existe aussi des déserts de glace, comme en Antarctique ! ❄️🏜️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi une île", "qu'est-ce qu'une île"],
    responses: ["Une île c'est un morceau de terre entouré d'eau de tous les côtés ! Comme la Corse ou Madagascar ! 🏝️", "C'est de la terre au milieu de l'eau ! Tu peux y aller en bateau ou en avion ! 🏝️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un fleuve", "qu'est-ce qu'un fleuve", "c'est quoi une rivière"],
    responses: ["Un fleuve c'est un grand cours d'eau qui se jette dans la mer ! En France on a la Seine, la Loire, le Rhône ! 🌊", "C'est comme une rivière géante qui va jusqu'à l'océan ! La Loire est le plus long fleuve de France ! 🏞️"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi l'europe", "qu'est-ce que l'europe"],
    responses: ["L'Europe c'est notre continent ! Il y a plein de pays comme la France, l'Espagne, l'Italie, l'Allemagne… 🇪🇺", "C'est le continent où on vit ! Il y a 44 pays en Europe ! 🌍"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi l'afrique", "qu'est-ce que l'afrique"],
    responses: ["L'Afrique c'est un continent immense ! On y trouve des lions, des éléphants, le Sahara et le Nil ! 🦁🌍", "C'est le deuxième plus grand continent ! Il y fait chaud et il y a des animaux incroyables ! 🐘"],
    intent: "EDUCATION" },

  // ━━━ ÉDUCATION — Corps humain ━━━
  { triggers: ["c'est quoi le cœur", "qu'est-ce que le cœur", "comment marche le cœur"],
    responses: ["Le cœur c'est un muscle qui bat tout le temps pour envoyer le sang dans tout ton corps ! Il bat environ 100 000 fois par jour ! ❤️", "C'est comme une pompe ! Il pousse le sang pour apporter de l'énergie partout dans ton corps ! 💓"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi le cerveau", "qu'est-ce que le cerveau"],
    responses: ["Le cerveau c'est le chef de ton corps ! Il contrôle tout : tes pensées, tes mouvements, tes souvenirs ! C'est le boss ! 🧠", "C'est comme un super ordinateur dans ta tête ! Il fait des milliards de calculs chaque seconde ! 🧠✨"],
    intent: "EDUCATION" },
  { triggers: ["combien d'os", "combien on a d'os"],
    responses: ["Tu as 206 os dans ton corps ! Et devine quoi, les bébés en ont encore plus : environ 300 ! Ils se soudent en grandissant ! 🦴", "206 os ! Le plus petit est dans ton oreille, il s'appelle l'étrier ! 🦴"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi on éternue", "c'est quoi un éternuement"],
    responses: ["On éternue pour expulser les microbes et la poussière de notre nez ! Un éternuement peut aller à 150 km/h ! Atchoum ! 🤧", "C'est ton nez qui se nettoie ! Quand quelque chose l'irrite, il fait atchoum pour tout éjecter ! 💨"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi on dort", "pourquoi il faut dormir"],
    responses: ["On dort pour que notre corps se répare et que notre cerveau range tous les souvenirs de la journée ! C'est super important ! 😴", "Le sommeil c'est comme recharger une batterie ! Ton corps et ton cerveau en ont besoin pour être en forme ! 🔋💤"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi on rêve", "c'est quoi les rêves"],
    responses: ["Les rêves c'est quand ton cerveau fait du cinéma pendant que tu dors ! Il mélange tes souvenirs et invente des histoires ! 🎬💭", "Personne ne sait exactement pourquoi, mais ton cerveau en profite pour trier les souvenirs ! C'est un peu magique ! ✨"],
    intent: "EDUCATION" },

  // ━━━ ÉDUCATION — Animaux ━━━
  { triggers: ["pourquoi les poissons vivent dans l'eau", "les poissons respirent"],
    responses: ["Les poissons ont des branchies au lieu de poumons ! Les branchies prennent l'oxygène dans l'eau ! 🐟", "Ils respirent grâce à leurs branchies qui filtrent l'oxygène de l'eau ! Comme nous avec l'air ! 🐠"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi les girafes ont un long cou", "le cou de la girafe"],
    responses: ["Les girafes ont un long cou pour manger les feuilles tout en haut des arbres ! Personne d'autre ne peut les atteindre ! 🦒🌳", "Leur cou peut faire 2 mètres ! Ça leur permet de manger là où les autres animaux ne peuvent pas ! 🦒"],
    intent: "EDUCATION" },
  { triggers: ["combien de pattes a une araignée", "les pattes de l'araignée"],
    responses: ["Les araignées ont 8 pattes ! C'est pour ça que ce ne sont pas des insectes, les insectes en ont 6 ! 🕷️", "Huit pattes ! Et elles ont aussi 8 yeux pour la plupart ! 🕷️👀"],
    intent: "EDUCATION" },
  { triggers: ["est-ce que les dauphins sont des poissons"],
    responses: ["Non ! Les dauphins sont des mammifères ! Ils respirent de l'air comme nous et allaitent leurs bébés ! 🐬", "Pas du tout ! Ce sont des mammifères ! Ils doivent remonter à la surface pour respirer ! 🐬"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un mammifère", "qu'est-ce qu'un mammifère"],
    responses: ["Un mammifère c'est un animal qui allaite ses bébés avec du lait ! Comme les chats, les chiens, les baleines et… nous ! 🐱🐶", "Ce sont des animaux à sang chaud qui ont des poils et nourrissent leurs bébés avec du lait ! On en est aussi ! 🧒"],
    intent: "EDUCATION" },
  { triggers: ["quel est l'animal le plus rapide", "l'animal le plus rapide"],
    responses: ["C'est le guépard ! Il peut courir à 120 km/h ! Plus vite qu'une voiture en ville ! 🐆💨", "Le guépard ! Il sprinte à 120 km/h mais seulement pendant quelques secondes ! 🐆"],
    intent: "EDUCATION" },
  { triggers: ["quel est le plus grand animal", "l'animal le plus grand"],
    responses: ["La baleine bleue ! Elle peut mesurer 30 mètres et peser 150 tonnes ! C'est le plus grand animal qui ait jamais existé ! 🐋", "C'est la baleine bleue ! Son cœur est gros comme une voiture ! 🐋💙"],
    intent: "EDUCATION" },

  // ━━━ ÉDUCATION — Divers ━━━
  { triggers: ["c'est quoi un robot", "qu'est-ce qu'un robot"],
    responses: ["Un robot c'est une machine programmée pour faire des choses toute seule ! Il y en a qui fabriquent des voitures et d'autres qui explorent Mars ! 🤖", "C'est une machine intelligente ! Certains peuvent parler, marcher et même jouer ! Comme moi un peu ! 🤖😊"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi internet", "qu'est-ce qu'internet"],
    responses: ["Internet c'est un réseau géant qui connecte les ordinateurs du monde entier ! C'est comme une toile d'araignée invisible ! 🌐🕸️", "C'est comme une bibliothèque magique où tu peux trouver des informations, des vidéos et parler avec des gens partout dans le monde ! 📚✨"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi l'électricité", "qu'est-ce que l'électricité"],
    responses: ["L'électricité c'est de l'énergie qui circule dans les fils ! C'est elle qui allume les lumières et fait marcher les appareils ! ⚡", "Ce sont des minuscules particules appelées électrons qui bougent très vite dans les câbles ! C'est comme un fleuve invisible d'énergie ! ⚡🔌"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi le feu brûle", "c'est quoi le feu"],
    responses: ["Le feu c'est une réaction chimique ! Il a besoin de trois choses : du combustible, de la chaleur et de l'oxygène ! C'est le triangle du feu ! 🔥", "Le feu se produit quand quelque chose de très chaud réagit avec l'air ! C'est pour ça que sans air, le feu s'éteint ! 🔥"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un fossile", "qu'est-ce qu'un fossile"],
    responses: ["Un fossile c'est la trace d'un animal ou d'une plante qui vivait il y a très longtemps ! C'est comme une empreinte dans la pierre ! 🦴🪨", "C'est quand un os ou une coquille se transforme en pierre avec le temps ! Ça prend des millions d'années ! 🦕🪨"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi un atome", "qu'est-ce qu'un atome"],
    responses: ["Un atome c'est le plus petit morceau de matière ! Tout est fait d'atomes : toi, moi, l'air, les étoiles ! C'est minuscule ! ⚛️", "C'est tellement petit qu'on ne peut pas le voir ! Des milliards de milliards d'atomes forment un grain de sable ! ⚛️"],
    intent: "EDUCATION" },
  { triggers: ["combien de couleurs dans l'arc-en-ciel", "les couleurs de l'arc-en-ciel"],
    responses: ["Il y a 7 couleurs ! Rouge, orange, jaune, vert, bleu, indigo et violet ! 🌈", "7 couleurs magiques ! Un moyen de s'en souvenir : chaque lettre de 'ROY G BIV' est une couleur en anglais ! 🌈"],
    intent: "EDUCATION" },
  { triggers: ["pourquoi la mer est salée", "la mer est salée"],
    responses: ["L'eau des rivières dissout les minéraux des roches, et ces minéraux arrivent dans la mer ! Avec le temps, ça fait beaucoup de sel ! 🧂🌊", "Les roches libèrent du sel depuis des millions d'années ! L'eau s'évapore mais le sel reste ! 🌊"],
    intent: "EDUCATION" },
  { triggers: ["c'est quoi le recyclage", "qu'est-ce que le recyclage", "pourquoi recycler"],
    responses: ["Le recyclage c'est transformer les déchets en nouvelles choses ! Une bouteille en plastique peut devenir un t-shirt ! ♻️👕", "C'est super important pour la planète ! Au lieu de jeter, on retransforme ! Le verre, le papier, le plastique, on peut tout recycler ! ♻️🌍"],
    intent: "EDUCATION" },
  { triggers: ["apprends-moi quelque chose", "apprends-moi un truc", "dis-moi un truc cool"],
    responses: ["Tu savais que les papillons goûtent avec leurs pieds ? Incroyable non ? 🦋😄", "Le savais-tu ? Un escargot peut dormir pendant 3 ans ! 🐌💤", "Fun fact : les flamants roses sont roses parce qu'ils mangent des crevettes ! 🦩🦐", "Tu savais que la foudre est 5 fois plus chaude que la surface du soleil ? ⚡☀️", "Incroyable : une pieuvre a 3 cœurs et du sang bleu ! 🐙💙", "Le savais-tu ? Les koalas dorment 22 heures par jour ! 🐨💤"],
    intent: "EDUCATION" },
];
